## 0- Lists

**1-** Create a list containing numbers form 1,...,5

In [ ]:
L=[1,2,3,4,5]

**2-** Create another list of numbers containing square of numbers form 1,...,5

In [ ]:
L2=[1,4,9,16,25]

**3-** Repeat the above two tasks for numbers 1,...,50

In [ ]:
Numbers=list(range(1,51))
print(Numbers)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50]


In [ ]:
Numbers2=[x**2 for x in Numbers]
print(Numbers2)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500]


**4-** Create a list, say ***eSquare***, which has only the squares of even numbers form 1,...,50.

In [ ]:
eSquare=[e**2 for e in Numbers if e%2==0]
print(eSquare)

[4, 16, 36, 64, 100, 144, 196, 256, 324, 400, 484, 576, 676, 784, 900, 1024, 1156, 1296, 1444, 1600, 1764, 1936, 2116, 2304, 2500]


**5-** Create a new list, say ***PV***, which has 'E' for even numbers and 'O' for odd numbers for numbers from 1,...,50.

In [ ]:
PV=['E' if x%2==0 else 'O' for x in Numbers2]
print(PV)

['O', 'E', 'O', 'E', 'O', 'E', 'O', 'E', 'O', 'E', 'O', 'E', 'O', 'E', 'O', 'E', 'O', 'E', 'O', 'E', 'O', 'E', 'O', 'E', 'O', 'E', 'O', 'E', 'O', 'E', 'O', 'E', 'O', 'E', 'O', 'E', 'O', 'E', 'O', 'E', 'O', 'E', 'O', 'E', 'O', 'E', 'O', 'E', 'O', 'E']


**6-** Find the length of eSquare

In [ ]:
print(len(eSquare))

25


**6-** Find the position of 196 in eSquare

In [ ]:
print(eSquare.index(196))

6


**7-** Check if number 576 is inside eSquare

In [ ]:
print(576 in eSquare)

True


**8-** Create two new variables, containing the max and min numbers inside eSquare

In [ ]:
max, min = max(eSquare), min(eSquare)
print(max,min)

2500 4


**9-** Swap the values of the above two variables

In [ ]:
min, max = max, min
print(min, max)

2500 4


**10-** Remove 196 from eSquare

In [ ]:
eSquare.remove(196)
print(eSquare)

[4, 16, 36, 64, 100, 144, 256, 324, 400, 484, 576, 676, 784, 900, 1024, 1156, 1296, 1444, 1600, 1764, 1936, 2116, 2304, 2500]


#1- Enumerate

Consider the following list:
['Apple', 'Banana', 'Orange', 'Watermelon', 'Plum', 'Grapes', 'Kiwi', 'Strawberry', 'Pear']

**1-** Create a list and name it ***fruits***

In [ ]:
fruits = ['Apple', 'Banana', 'Orange', 'Watermelon', 'Plum', 'Grapes', 'Kiwi', 'Strawberry', 'Pear']

**2-** Sort the above list in ascending alphabetical order

In [ ]:
fruits.sort()
print("The sorted list is:", fruits)

The sorted list is: ['Apple', 'Banana', 'Grapes', 'Kiwi', 'Orange', 'Pear', 'Plum', 'Strawberry', 'Watermelon']


**3-** To the sorted list, for each element prefix the value by its position

In [ ]:
NumberedList = [str(i+1)+'.'+ j for i,j in enumerate(fruits)]
print(NumberedList)

['1.Apple', '2.Banana', '3.Grapes', '4.Kiwi', '5.Orange', '6.Pear', '7.Plum', '8.Strawberry', '9.Watermelon']


#2- Zip

**1-** Consider the following list:  
[['Apple', 'Banana', 'Orange'], ['Watermelon', 'Plum', 'Grapes', 'Kiwi'], ['Strawberry', 'Pear', 'Mango']]
. Create a new list containing all the 'fruits'


In [ ]:
fruits = [['Apple', 'Banana', 'Orange'], ['Watermelon', 'Plum', 'Grapes', 'Kiwi'], ['Strawberry', 'Pear', 'Mango']]
allFruits = [i for innerlist in fruits for i in innerlist]
print(allFruits)

['Apple', 'Banana', 'Orange', 'Watermelon', 'Plum', 'Grapes', 'Kiwi', 'Strawberry', 'Pear', 'Mango']


**2-** Create a new list, say zipZap, containing tuple of fruits name followed by length of the name

In [ ]:
lenFruits = [len(i) for i in allFruits]
print(lenFruits)

[5, 6, 6, 10, 4, 6, 4, 10, 4, 5]


In [ ]:
zipZap = list(zip(allFruits, lenFruits))
print(zipZap)

[('Apple', 5), ('Banana', 6), ('Orange', 6), ('Watermelon', 10), ('Plum', 4), ('Grapes', 6), ('Kiwi', 4), ('Strawberry', 10), ('Pear', 4), ('Mango', 5)]


**3-** Iterate over zipZap and print all the elements

In [ ]:
for i in zipZap:
    print(i[0],i[1])


Apple 5
Banana 6
Orange 6
Watermelon 10
Plum 4
Grapes 6
Kiwi 4
Strawberry 10
Pear 4
Mango 5


**4-** Iterate over zipZap and print the index and all the corresponding elements

In [ ]:
for i,j in enumerate(zipZap):
  print(i,j[0],j[1])

0 Apple 5
1 Banana 6
2 Orange 6
3 Watermelon 10
4 Plum 4
5 Grapes 6
6 Kiwi 4
7 Strawberry 10
8 Pear 4
9 Mango 5


#3- Dictionaries

In [ ]:
fruits=['Apple', 'Banana', 'Orange', 'Watermelon', 'Plum', 'Grapes', 'Kiwi', 'Strawberry', 'Pear', 'Mango']
prices=[47, 27, 35, 13, 28, 10, 30, 56, 15, 25]

**1-** Create a dictionary, say ***book1***, which has fruits as keys, and prices as values

In [ ]:
book1 = dict(zip(fruits,prices))
#book1 = list(zip(fruits,prices))
print(book1)

{'Apple': 47, 'Banana': 27, 'Orange': 35, 'Watermelon': 13, 'Plum': 28, 'Grapes': 10, 'Kiwi': 30, 'Strawberry': 56, 'Pear': 15, 'Mango': 25}


**2-** Loop over all the key & value pairs of book1 and print them

In [ ]:
for i,j in book1.items():
  print(f'The price of {i} is {j}')

The price of Apple is 47
The price of Banana is 27
The price of Orange is 35
The price of Watermelon is 13
The price of Plum is 28
The price of Grapes is 10
The price of Kiwi is 30
The price of Strawberry is 56
The price of Pear is 15
The price of Mango is 25


**3-** Create a dictionary, say ***book2***, which has fruits as values, and unique numbers as keys

In [ ]:
uniqueNumbers = list(range (len(fruits)))
book2 = dict(zip(uniqueNumbers,fruits))
print(book2)

{0: 'Apple', 1: 'Banana', 2: 'Orange', 3: 'Watermelon', 4: 'Plum', 5: 'Grapes', 6: 'Kiwi', 7: 'Strawberry', 8: 'Pear', 9: 'Mango'}


**4-** Display book2 and ask the user to pick a number. Then display the price of the fruit using book1.

In [ ]:
for i,j in book2.items():
  print(f"{i}:{j}")

#itemSelected = input("Enter the number of the fruit you want to buy: ")
#itemSelected = int(itemSelected)

#fruitSelected = book2[itemSelected]
#priceSelected = book1[fruitSelected]

#print(f'You have selected {fruitSelected}')
#print(f'The price per KG of {fruitSelected} is {priceSelected}$')


0:Apple
1:Banana
2:Orange
3:Watermelon
4:Plum
5:Grapes
6:Kiwi
7:Strawberry
8:Pear
9:Mango


#4- String Methods

we are reviewing python programming topics in ise 291. it is the most popular language for data scientists. also, it is a good general purpose programming language.

Do the following:


1. Breakdown the given text into list of sentences
2. Capitalize the first word in each sentence
3. Replace 'ise' with 'ISE" everywhere
4. Join all the above sentences into a new text
5. Print the new text.

In [ ]:
text = """we are reviewing python programming topics in ise 291.
it is the most popular language for data scientists.
also, it is a good general purpose programming language."""

In [ ]:
sentences = text.split('.')
sentences.pop(-1)
print(sentences)

sentences1 =  [s.strip().capitalize().replace('ise','ISE') for s in sentences]
print(sentences1)

['we are reviewing python programming topics in ise 291', '\nit is the most popular language for data scientists', '\nalso, it is a good general purpose programming language']
['We are reviewing python programming topics in ISE 291', 'It is the most popular language for data scientists', 'Also, it is a good general purpose programming language']


#4- Lambda & Map

1. Python's lambda() function is a small **anonymous** function, which can take any number of arguments, but can only have one expression.
2. Python's map() function apply one function to each element of an **iterable** like list, tuple in Python.


In [ ]:
print((lambda x,y,z: x**y+z)(3,2,1))

10


In [ ]:
print((lambda x : f"{x} is an even number." if x%2 == 0 else f"{x} is an odd number.")(35))

35 is an odd number.


In [ ]:
#number = input("Enter the nubmer you want to check: ")
#number = int(number)
#print(f"{number} is an even number." if number%2 == 0 else f"{number} is an odd  number.")

In [ ]:
l = list(range(13))
print(l)
def square(x):
  return x**2

l2 = list(map(square, l))
print(l2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144]


In [ ]:
l3 = list(map((lambda x : x**2), L))
print(l3)

[1, 4, 9, 16, 25]


In [ ]:
list1 = list(range(6))
list2 = [i**2 for i in list1]
print(list1)
print(list2)
listSub = list(map((lambda x,y : x - y),list1, list2)) 
print(listSub)

[0, 1, 2, 3, 4, 5]
[0, 1, 4, 9, 16, 25]
[0, 0, -2, -6, -12, -20]


In [ ]:
square1 = list(map((lambda x: x**2 if x%2==0 else None), list(range(21))))
print(square)

<function square at 0x7f26765d3d30>


#5- Numpy Library

### 1- Creating Numpy Arrays

**1.** Create an integer array of 10 elements filled with all zeros

In [ ]:
import numpy as np
np.zeros(10, int)

list1 = [0 for x in range(10)]
print(list1)
print(type(list1))

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
<class 'list'>


3. Create a 3x5 floating-point array filled with ones

In [ ]:
np.ones((3,5), dtype = 'float')

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

4. Create a 3x5 array filled with pi values

In [ ]:
print(np.full((3,5), np.pi))

[[3.14159265 3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265 3.14159265]
 [3.14159265 3.14159265 3.14159265 3.14159265 3.14159265]]


5. Create a 3x3 array of uniformly distributed random values between 0 and 1

In [ ]:
#np.random.seed(0)
print(np.random.random((3,3)))

[[0.2239085  0.15866742 0.14401781]
 [0.61019402 0.16896143 0.83253044]
 [0.90585743 0.63591544 0.10795808]]


6. Create a 3x3 array of random integers in the interval [0, 10)


In [ ]:
np.random.randint(0, 10, (3,3))

array([[7, 9, 7],
       [1, 8, 3],
       [9, 5, 6]])

**7.** Create a 3x3 identity matrix

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**8.** Create an array of 11 elements uniformly dividing the interval [0,1]

In [ ]:
np.linspace(0,50,20)

array([ 0.        ,  2.63157895,  5.26315789,  7.89473684, 10.52631579,
       13.15789474, 15.78947368, 18.42105263, 21.05263158, 23.68421053,
       26.31578947, 28.94736842, 31.57894737, 34.21052632, 36.84210526,
       39.47368421, 42.10526316, 44.73684211, 47.36842105, 50.        ])

### 2- Numpy Array Attributes

Numpy array have the following attributes:

1. ndim (the number of dimensions),
2. shape (the size of each dimension), and
3. size (the total size of the array).

**1.** Create a random one-dimensional array (x1), and check all the above attributes

In [ ]:
#np.random.seed(0)
x1 = np.random.randint(10, size=6)
print(x1)
print(f"The dimention of x1 is {x1.ndim}")
print(f"The shape of x1 is {x1.shape}")
print(f"The size of x1 is {x1.size}")

[8 1 2 9 9 0]
The dimention of x1 is 1
The shape of x1 is (6,)
The size of x1 is 6


2. Create a random two-dimensional array (x2), and check all the above attributes

In [ ]:
np.random.seed(0)
x2 = np.random.randint(10, size=(3,4))
print(x2)
print(f"The dimention of x2 is {x2.ndim}")
print(f"The shape of x2 is {x2.shape}")
print(f"The size of x2 is {x2.size}")

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
The dimention of x2 is 2
The shape of x2 is (3, 4)
The size of x2 is 12


### 3- Indexing

In [ ]:
np.random.seed(0)
x1 = np.random.randint(10, size = 6)
print(x1)

print(f"indicies = {list(range(6))}")
print(f"array: {x1.tolist()}")
print(x1[0],x1[4],x1[-1],x1[-2])

[5 0 3 3 7 9]
indicies = [0, 1, 2, 3, 4, 5]
array: [5, 0, 3, 3, 7, 9]
5 7 9 7


In [ ]:
np.random.seed(0)
x2 = np.random.randint(50, size = (3,4))
print(x2)
print(x2[1][3], x2[2][3], x2[0][2])

[[44 47  0  3]
 [ 3 39  9 19]
 [21 36 23  6]]
19 6 0


### 4- Slicing

### 1D arrays

Slicing refer to selecting/extracting a sub-array from a given array. As an example for 1d arrays, do the following tasks:

**1.** Create a random 1d numpy array of size 10

In [ ]:
np.random.seed(0)
x1 = np.random.randint(10, size = 8)
print(x1)

[5 0 3 3 7 9 3 5]


**2.** Display the first five elements

In [ ]:
#for i in list(range(5)):
#  print(x1[i])

print(x1[:5])
x1[:5]

[5 0 3 3 7]


array([5, 0, 3, 3, 7])

**3.** Display elements from index 5 to end

In [ ]:
x1[5:]

array([9, 3, 5])

**4.** Display elements from index 4 to 6

In [ ]:
x1[4:7]

array([7, 9, 3])

**5.** Display alternate elements starting from the first element

In [ ]:
print(x1)
x1[::2]

[5 0 3 3 7 9 3 5]


array([5, 3, 7, 3])

**6.** Display alternate elements starting from the second element

In [ ]:
print(x1)
x1[1::2]

[5 0 3 3 7 9 3 5]


array([0, 3, 9, 5])

**7.** Display elements starting from fourth element from the end and ending at last but one element

In [ ]:
print(x1)
x1[-4:-1]

[5 0 3 3 7 9 3 5]


array([7, 9, 3])

**8.** Display all element in the reverse order of indices

In [ ]:
print(x1)
x1[::-1]

[5 0 3 3 7 9 3 5]


array([5, 3, 9, 7, 3, 3, 0, 5])

### 2D arrays

**1.** Create a random 2d numpy array of size 3x4

In [ ]:
np.random.seed(0)
x2 = np.random.randint(10, size = (3,4))
print(x2)


[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


**2.** Display first two rows, first three columns

In [ ]:
x2[:2,:3]

array([[5, 0, 3],
       [7, 9, 3]])

**3.** Display all rows, and every other column

In [ ]:
x2[:,:]

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6]])

**4.** Display all rows and columns in the reverse order

In [ ]:
x2[::-1,::-1]

array([[6, 7, 4, 2],
       [5, 3, 9, 7],
       [3, 3, 0, 5]])

**5.** Display first column

In [ ]:
x2[:,:1]

array([[5],
       [7],
       [2]])

**6.** Display first row 

In [ ]:
print(x2)
x2[0,:]

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


array([5, 0, 3, 3])

**7.** From the third row, display  column 3 element, then column 1 then column 2

In [ ]:
x2[2,[2,0,1]]

array([7, 2, 4])

**8.** Display second and following row elements in order of column 3, then column 1 then column 2

In [ ]:
print(x2)
x2[1:,[2,0,1]]

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]


array([[3, 7, 9],
       [7, 2, 4]])

### 5- Sorting

Numpy .sort() method sorts an array in-place. The sorting is done row/column wise, and order/preference can be provided too. As an example, do the following:

1. Create a 1D random array of size 6, and sort it. Print the corresponding original indices in the sorted array.

In [ ]:
np.random.seed(0)
x1 = np.random.randint(30, size = 16)
print(x1)
print(f"Original indices  : {list(range(16))}")
print(f"Given array       : {x1.tolist()}")
print(f"Sorted array      : {np.sort(x1).tolist()}")
print(f"Sorted idicies    : {np.argsort(x1).tolist()}")

[12 15 21  0  3 27  3  7  9 19 21 18  4 23  6 24]
Original indices  : [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]
Given array       : [12, 15, 21, 0, 3, 27, 3, 7, 9, 19, 21, 18, 4, 23, 6, 24]
Sorted array      : [0, 3, 3, 4, 6, 7, 9, 12, 15, 18, 19, 21, 21, 23, 24, 27]
Sorted idicies    : [3, 4, 6, 12, 14, 7, 8, 0, 1, 11, 9, 2, 10, 13, 15, 5]


2. Create a random 2D numpy array of size 7x6. Sort row wise

In [ ]:
np.random.seed(0)
x2 = np.random.randint(30, size = (7, 6))
print(x2)
print("___"*10)

x2.sort(axis=0)
print(x2)

[[12 15 21  0  3 27]
 [ 3  7  9 19 21 18]
 [ 4 23  6 24 24 12]
 [26  1  6  7 23 14]
 [24 17  5 25 13  8]
 [ 9 20 19 16 19  5]
 [15 15  0 18  3 24]]
______________________________
[[ 3  1  0  0  3  5]
 [ 4  7  5  7  3  8]
 [ 9 15  6 16 13 12]
 [12 15  6 18 19 14]
 [15 17  9 19 21 18]
 [24 20 19 24 23 24]
 [26 23 21 25 24 27]]


3. Create a random 2d numpy array of size 7x6. Sort column wise

In [ ]:
np.random.seed(10)
x2 = np.random.randint(20, size=(7,6))
print(x2)
print('____'*10)
x2.sort(axis=1)
print(x2)

[[ 9  4 15  0 17 16]
 [17  8  9  0 10  8]
 [ 4 19 16  4 15 11]
 [11  1  8  4 14 17]
 [19 13  5 13 19 13]
 [12  1  4 18 13 11]
 [10  9 15 18 16  7]]
________________________________________
[[ 0  4  9 15 16 17]
 [ 0  8  8  9 10 17]
 [ 4  4 11 15 16 19]
 [ 1  4  8 11 14 17]
 [ 5 13 13 13 19 19]
 [ 1  4 11 12 13 18]
 [ 7  9 10 15 16 18]]


### 6- Copy of Array

In [ ]:
np.random.seed(0)
x2 = np.random.randint(20, size=(4,6))
print(f"x2 is:\n{x2}")
print("___"*10)
x2_copy = x2
x22 = x2.copy()
print(f"x22_copy is:\n{x22}")
print("___"*10)

x22[0,1:3] = [4,4]
print(f"x2_copy modified is:\n {x22}")

x2 is:
[[12 15  0  3  3  7]
 [ 9 19 18  4  6 12]
 [ 1  6  7 14 17  5]
 [13  8  9 19 16 19]]
______________________________
x22_copy is:
[[12 15  0  3  3  7]
 [ 9 19 18  4  6 12]
 [ 1  6  7 14 17  5]
 [13  8  9 19 16 19]]
______________________________
x2_copy modified is:
 [[12  4  4  3  3  7]
 [ 9 19 18  4  6 12]
 [ 1  6  7 14 17  5]
 [13  8  9 19 16 19]]


## 7- Reshaping

Numpy .reshape method gives a new shape to an existing array without changing its data. As an exmaple, do the following task:

1. Create a 1d random array of size 10.

In [ ]:
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10,size=10) # One-dimensional array
print(x1)

[5 0 3 3 7 9 3 5 2 4]


2. Reshape the 1d array into size 5x2

In [ ]:
x11 = x1.reshape(5,2)
print(x11)

[[5 0]
 [3 3]
 [7 9]
 [3 5]
 [2 4]]


3. Reshape the 1d array into size 2x5

In [ ]:
print(x1.reshape(2,5))
print(x1.reshape(5,-1))

[[5 0 3 3 7]
 [9 3 5 2 4]]
[[5 0]
 [3 3]
 [7 9]
 [3 5]
 [2 4]]


## 8- Concatenate/Split

Concatenate means joining, and Numpy's .concatenate() function is used to join two or more arrays of the same shape along a specified axis. Numpy's .vstack() (.hstack()) can be used for row wise (column wise) joining. Numpy's split/vsplit/hsplit methods are for breaking/splitting the array, opposite to the concatenation.

For example, see the code in the following cells:

In [ ]:
x = np.array([1,2,3])
y = np.array([3,2,1])
z = np.array([9,9,9])

print(np.concatenate((x,y,z)))   # to join all 1d arrays along axis 0

[1 2 3 3 2 1 9 9 9]


In [ ]:
x = np.array([1,2,3])
y = np.array([3,2,1])
z = np.array([9,9,9])

print(np.vstack((x,y,z)))
print("___"*20)
print(np.hstack((x,y,z)))

[[1 2 3]
 [3 2 1]
 [9 9 9]]
____________________________________________________________
[1 2 3 3 2 1 9 9 9]


In [ ]:
x = [1,2,3,99,99,3,2,1]
print(x)

x1, x2, x3 = np.split(x, [3,7])
print(x1, x2, x3)

[1, 2, 3, 99, 99, 3, 2, 1]
[1 2 3] [99 99  3  2] [1]


## 9- Vectorized Operations

Vectorized operations are perhaps the most crucial factor to the wide usage of Numpy library. Vectorized operations simply put are those operations that can be done on arrays without using loops.

1. Create a random id array, and add, subtract,multiply and divide all the elements with 5

In [ ]:
np.random.seed(10)
id = np.random.randint(20, size=(10))
print(f"Original: {id}")
print("__"*30)
print(f"Addition: {id+5}")
print(f"Sub: {id-5}")
print(f"Mult: {id*5}")
print(f"Div: {id/5}")

Original: [ 9  4 15  0 17 16 17  8  9  0]
____________________________________________________________
Addition: [14  9 20  5 22 21 22 13 14  5]
Sub: [ 4 -1 10 -5 12 11 12  3  4 -5]
Mult: [45 20 75  0 85 80 85 40 45  0]
Div: [1.8 0.8 3.  0.  3.4 3.2 3.4 1.6 1.8 0. ]


2. Take the square of all elements.
3. Find remainder w.r.t 2 for all elements.

In [ ]:
print(f"Original: {id}")
print("__"*30)
print(f"Sqr: {id**2}")
print(f"Reminder: {id%2}")

Original: [ 9  4 15  0 17 16 17  8  9  0]
____________________________________________________________
Sqr: [ 81  16 225   0 289 256 289  64  81   0]
Reminder: [1 0 1 0 1 0 1 0 1 0]


4. Transform the array as: $-(\frac{x}{2}+1)^2$, where $x$ is the random 1d array.

In [ ]:
new_id = -(id*0.5+1)**2
print(f"new_id:{new_id}")

new_id:[-30.25  -9.   -72.25  -1.   -90.25 -81.   -90.25 -25.   -30.25  -1.  ]


## 10- Ufuncs

A universal function (or ufunc for short) is a vectorized wrapper for a function that takes a fixed number of specific inputs and produces a fixed number of specific outputs.

In [ ]:
x = np.array([-2,-1,0,1,2])

print(x) # the original array

print('-'*30)
print(np.abs(x))  # convert all elements to +ve numbers
print(np.sqrt(np.abs(x)))  # get square-roots of all abs(elements)
print(np.min(x))  # get the min value
print(np.max(x))  # get the max value
print(np.sum(x))  # get the sum of all value

[-2 -1  0  1  2]
------------------------------
[2 1 0 1 2]
[1.41421356 1.         0.         1.         1.41421356]
-2
2
0


## 11- Broadcasting

Vectorization involving multiple arrays can be done. Vectorization follows broadcasting rules. The key broadcasting rule is: In order to broadcast, the size of the trailing axes for both arrays in an operation must either be the same size or one of them must be one. In rough sense, what it means is:

1. If two arrays of same dimensions have the same shape, then corresponding elements can be broadcasted.
2. If the arrays do not have the same dimensions, prepend the shape of the lower dimension array with 1s until both arrays have the same dimensions.
3. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension.

1. Add/multiply corresponding elements of two different sized arrays.

In [ ]:
A = np.ones((5,4), dtype = "int")
print(A)
print("-"*20)
B = np.arange(4, dtype = "int")
print(B)
print("-"*20)
print(f'The dimentions of the arrays are:{A.shape}{B.shape}')
print("-"*20)
print(f'   The sum:\n {A+B}')
print("-"*20)
print(f'   The dot:\n {A*B}')

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
--------------------
[0 1 2 3]
--------------------
The dimentions of the arrays are:(5, 4)(4,)
--------------------
   The sum:
 [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
--------------------
   The dot:
 [[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]


## 12- Masking

Masked array is an array of booleans that determines for each element of the associated array whether the value is valid or not. The masked arrays are obtained using different conditions. Numpy array comparison are vectorized too.

In [ ]:
x = np.array([1,2,3,4,5,6])

print(x<3)  # less than
print(x>3)  # greater than
print(x<=3) #less than or equal
print(x>=3) #greater than or equal
print(x!=3) #not equal
print(x==3) #equal

[ True  True False False False False]
[False False False  True  True  True]
[ True  True  True False False False]
[False False  True  True  True  True]
[ True  True False  True  True  True]
[False False  True False False False]


In [ ]:
x[x<3]

array([1, 2])

In [ ]:
x[(x > 2) & (x < 5)]

array([3, 4])